[package]
name = "ultimate_tic_tac_toe_tui"
version = "0.1.0"
authors = ["Athir Saleem <noc7c9@gmail.com>"]

[dependencies]
ultimate_tic_tac_toe = { version = "0.1.0", path = "../" }
crossterm = "0.4.2"
